
services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/html
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - "3316:3306"
    env_file:
#      - ./src/env.prod
      - ./env/mysql.env
#    environment:
#      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_DATABASE: '${DB_DATABASE}'
#      MYSQL_USER: '${DB_USERNAME}'
#      MYSQL_PASSWORD: '${DB_PASSWORD}'
#      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  composer:
    build:
      context: dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
